# config/packages/security.yaml
security:
    # Configuraci贸n para la autenticaci贸n JWT
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        main:
            # Protege las rutas de actualizaci贸n y eliminaci贸n con JWT
            jwt: ~
            provider: app_user_provider
            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/libros, roles: ROLE_USER }
        - { path: ^/usuarios, roles: ROLE_USER }
        - 
            path: ^/libros/{id}
            methods: [PUT, DELETE]
            roles: ROLE_USER
        - 
            path: ^/usuarios/{id}
            methods: [DELETE]
            roles: ROLE_USER



